baseurl      = "https://www.shanesveller.com"
languageCode = "en-us"
title        = "Shane Sveller"
subtitle     = "AWS, Chef, Docker, Elixir, Jenkins, Kubernetes, DevOps"

canonifyURLs    = true
disqusShortname = "shanesveller"
uglyurls        = false

pygmentsCodeFences = true

[params]
    author         = "Shane Sveller"
    authorlinkedin = "https://www.linkedin.com/in/shanesveller"
    authortwitter  = "shanesveller"
    copyright      = "&copy; 2017 Shane Sveller"
    description    = "Senior DevOps Engineer at Raise Marketplace"
    gaid           = "UA-2369454-1"
    sidebartitle   = "Shane Sveller"
    sidebartagline = "AWS, Chef, Docker, Elixir, Jenkins, Kubernetes, DevOps"

[permalinks]
    blog = "/blog/:year/:month/:day/:title"

[[menu.main]]
    name = "Blog"
    url  = "/blog/"


[[menu.social]]
    pre        = "<i class ='fa fa-github'></i>"
    url        = "https://github.com/shanesveller"
    identifier = "github"

[[menu.social]]
    pre        = "<i class ='fa fa-key'></i>"
    url        = "https://keybase.io/shanesveller"
    identifier = "keybase"

[[menu.social]]
    pre        = "<i class ='fa fa-linkedin'></i>"
    url        = "https://www.linkedin.com/in/shanesveller"
    identifier = "linkedin"

[[menu.social]]
    pre        = "<i class ='fa fa-twitter'></i>"
    url        = "http://www.twitter.com/shanesveller"
    identifier = "twitter"
